import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const paybooc = localFont({
  src: [
    {
      path: "../../public/fonts/paybooc Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/paybooc Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/paybooc ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-paybooc",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NaverMapProvider } from "@/components/providers/NaverMapProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${paybooc.variable} antialiased font-sans`}>
        <NaverMapProvider>{children}</NaverMapProvider>
      </body>
    </html>
  );
}
